// Shared product catalog
export const PRODUCTS = [
  { slug: 'back-to-teens-tablets', name: 'ZeroHarm Back To Teens Tablets', tagline: 'Male Vigour, Performance & Stamina', category: "Men's Health", img: 'https://www.zeroharm.in/cdn/shop/files/1_20_b88cdbff-1a77-4fa1-b705-f8446ea84a0b.png?v=1766164278&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/1_20_b88cdbff-1a77-4fa1-b705-f8446ea84a0b.png?v=1766164278&width=533','https://www.zeroharm.in/cdn/shop/files/2_2.jpg?v=1766167097&width=533','https://www.zeroharm.in/cdn/shop/files/1_29_aab564f1-f549-45da-82ff-0765e20b0907.png?v=1766208931&width=533'], rating: 4.57, reviews: 1079, price: 999, oldPrice: 1199, discount: 17, ingredients: ['Horny Goat Weed', 'Maca Root Extract', 'Ashwagandha', 'Shilajit'], benefits: ['Boosts male vigour and stamina', 'Enhances performance naturally', 'Supports testosterone levels', 'Improves energy and endurance'], description: 'A clinically-tested nano-formulated blend of Horny Goat Weed, Maca Root and time-tested Ayurvedic herbs designed to boost male vigour, stamina and performance. 60 plant-based tablets, no side effects.', servings: '60 Tablets', dosage: '2 tablets daily with water' },
  { slug: 'narie-boomup-capsules', name: 'Narie BoomUp Ayurvedic Capsules', tagline: 'Natural Curve Enhancement', category: "Women's Health", img: 'https://www.zeroharm.in/cdn/shop/files/narie-boomup-ayurvedic-breast-increase-capsules-8997401.jpg?v=1766165339&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/narie-boomup-ayurvedic-breast-increase-capsules-8997401.jpg?v=1766165339&width=533'], rating: 4.26, reviews: 53, price: 999, oldPrice: 1499, discount: 33, ingredients: ['Gotu Kola','Fenugreek Seeds','Ashwagandha','Pueraria Mirifica'], benefits: ['Natural shape enhancement','Hormonal balance support','Plant-based formulation','100% Ayurvedic'], description: 'A unique Ayurvedic blend for natural fullness, shape and volume. Crafted with herbs known for hormonal support.', servings: '60 Capsules', dosage: '2 capsules daily after meals' },
  { slug: 'gut-army-prebiotics-probiotics-capsules', name: 'Gut Army Prebiotic & Probiotic Capsules', tagline: '100 Billion CFU | 10 Strains', category: 'Gut Health', img: 'https://www.zeroharm.in/cdn/shop/files/GutarmyFi-02.jpg?v=1766166028&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/GutarmyFi-02.jpg?v=1766166028&width=533'], rating: 4.59, reviews: 1142, price: 999, oldPrice: 1199, discount: 17, ingredients: ['10 Probiotic Strains','Prebiotic Fiber','Lactobacillus','Bifidobacterium'], benefits: ['Improves digestion','Boosts immunity','Reduces bloating','Supports gut-brain axis'], description: 'A daily synbiotic with 100 billion CFU across 10 powerful strains plus prebiotic fiber. Rebuild your gut, rebuild your life.', servings: '30 Capsules', dosage: '1 capsule daily on empty stomach' },
  { slug: 'shilajit-with-ashwagandha-tablets', name: 'Himalayan Shilajit With Ashwagandha & Safed Musli', tagline: 'Strength & Vigour | Plant-Based', category: "Men's Health", img: 'https://www.zeroharm.in/cdn/shop/files/2_2.jpg?v=1766167097&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/2_2.jpg?v=1766167097&width=533'], rating: 4.58, reviews: 1409, price: 1300, oldPrice: 1899, discount: 32, ingredients: ['Pure Himalayan Shilajit','Ashwagandha','Safed Musli','Fulvic Acid'], benefits: ['Increases strength & stamina','Enhances vigour naturally','Anti-fatigue support','Rich in fulvic acid'], description: 'Premium Himalayan Shilajit nano-fused with Ashwagandha and Safed Musli — your daily dose of raw mountain energy.', servings: '60 Tablets', dosage: '2 tablets daily' },
  { slug: 'narie-fertility-formula', name: 'Narie Fertility Formula Tablets', tagline: 'Conceive Naturally', category: "Women's Health", img: 'https://www.zeroharm.in/cdn/shop/files/ayurvedic-zeroharm-narie-fertility-formula-tablets-to-conceive-naturally-9203153.jpg?v=1766167594&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/ayurvedic-zeroharm-narie-fertility-formula-tablets-to-conceive-naturally-9203153.jpg?v=1766167594&width=533','https://www.zeroharm.in/cdn/shop/files/f1_1.webp?v=1773747564&width=533'], rating: 4.58, reviews: 1333, price: 1399, oldPrice: 1499, discount: 7, ingredients: ['Shatavari','Chaste Berry','Ashoka','Lodhra'], benefits: ['Supports reproductive health','Balances hormones','Improves ovulation','100% plant-based'], description: 'An Ayurvedic fertility blend formulated by experts to support natural conception. Trusted by 1300+ women.', servings: '60 Tablets', dosage: '2 tablets daily' },
  { slug: 'lung-detox-tablets', name: 'Holo Lung Detox Tablets', tagline: 'Cleanse & Strengthen Lungs', category: 'Lung Health', img: 'https://www.zeroharm.in/cdn/shop/files/1_29_aab564f1-f549-45da-82ff-0765e20b0907.png?v=1766208931&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/1_29_aab564f1-f549-45da-82ff-0765e20b0907.png?v=1766208931&width=533'], rating: 4.66, reviews: 342, price: 1089, oldPrice: 1499, discount: 27, ingredients: ['Mulethi','Echinacea','Tulsi','Vasaka'], benefits: ['Detoxifies lungs','Improves breathing','Builds immunity','Reduces inflammation'], description: 'A potent herbal nano-formula to detox, repair and strengthen lung function naturally.', servings: '60 Tablets', dosage: '2 tablets daily after meals' },
  { slug: 'blood-purifis', name: 'Ayurvedic Blood Purifier For Acne', tagline: '6-Herb Nano Formula', category: 'Beauty', img: 'https://www.zeroharm.in/cdn/shop/files/ayurvedic-blood-purifier-for-acne-6-herb-nano-formula-1924988.jpg?v=1766165506&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/ayurvedic-blood-purifier-for-acne-6-herb-nano-formula-1924988.jpg?v=1766165506&width=533'], rating: 4.83, reviews: 64, price: 899, oldPrice: 1199, discount: 25, ingredients: ['Neem','Manjistha','Turmeric','Giloy','Khadira','Sariva'], benefits: ['Clears acne from within','Purifies blood','Glow-boosting','Anti-inflammatory'], description: 'A 6-herb nano blend that purifies the blood — your skin\'s root-cause solution to acne, breakouts and dullness.', servings: '60 Tablets', dosage: '1-2 tablets daily' },
  { slug: 'carb-cutter', name: 'Carb Cutter', tagline: 'Smart Glucose Control', category: 'Diabetic Care', img: 'https://www.zeroharm.in/cdn/shop/files/carb-cutter-4435497.jpg?v=1766168308&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/carb-cutter-4435497.jpg?v=1766168308&width=533'], rating: 4.88, reviews: 164, price: 1449, oldPrice: 1699, discount: 15, ingredients: ['Cinnamon','Berberine','Bitter Melon','Fenugreek'], benefits: ['Reduces post-meal glucose spikes','Improves insulin sensitivity','Supports weight goals','Natural carb-blocker'], description: 'Reduce post-meal glucose spikes naturally. A daily Ayurvedic insurance for carb lovers.', servings: '60 Capsules', dosage: '1 capsule before high-carb meals' },
  { slug: 'holo-hypertens', name: 'Holo Hypertens', tagline: 'Healthy Blood Pressure', category: 'Heart Health', img: 'https://www.zeroharm.in/cdn/shop/files/holo-hypertens-3841161.jpg?v=1766165479&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/holo-hypertens-3841161.jpg?v=1766165479&width=533'], rating: 4.82, reviews: 39, price: 999, oldPrice: 1399, discount: 29, ingredients: ['Pomegranate','Hibiscus','Garlic','Arjuna'], benefits: ['Supports healthy BP','Heart-friendly','Natural vasodilator','Antioxidant rich'], description: 'A heart-healthy nano formula crafted to support optimal blood pressure naturally.', servings: '60 Tablets', dosage: '2 tablets daily' },
  { slug: 'holo-piles-care', name: 'Holo Piles Care', tagline: 'Soothes & Heals Naturally', category: 'Gut Health', img: 'https://www.zeroharm.in/cdn/shop/files/holo-piles-care-4678226.jpg?v=1766168363&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/holo-piles-care-4678226.jpg?v=1766168363&width=533'], rating: 4.86, reviews: 21, price: 1199, oldPrice: 1499, discount: 20, ingredients: ['Triphala','Haritaki','Nagkesar','Daruharidra'], benefits: ['Relieves piles discomfort','Eases bowel movement','Anti-inflammatory','Heals naturally'], description: 'Comprehensive Ayurvedic care for piles — relief, repair, prevention.', servings: '60 Capsules', dosage: '2 capsules daily' },
  { slug: 'magnesium-glycinate-120-capsules', name: 'Magnesium Glycinate Capsules', tagline: 'Sleep, Calm & Recovery', category: 'Wellness', img: 'https://www.zeroharm.in/cdn/shop/files/magnesium-glycinate-capsules-4754965.jpg?v=1766165396&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/magnesium-glycinate-capsules-4754965.jpg?v=1766165396&width=533'], rating: 4.74, reviews: 77, price: 899, oldPrice: 1499, discount: 40, ingredients: ['Magnesium Glycinate','Moringa Extract'], benefits: ['Improves sleep quality','Reduces stress','Muscle recovery','Bone health'], description: 'Highly bioavailable magnesium glycinate enriched with moringa — for sleep, stress and recovery.', servings: '120 Capsules', dosage: '1-2 capsules at bedtime' },
  { slug: 'narie-desire-lift', name: 'Narie Desire Lift', tagline: 'Reignite Intimacy', category: "Women's Health", img: 'https://www.zeroharm.in/cdn/shop/files/narie-desire-lift-3347406.jpg?v=1766165317&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/narie-desire-lift-3347406.jpg?v=1766165317&width=533'], rating: 4.86, reviews: 44, price: 949, oldPrice: 1499, discount: 37, ingredients: ['Maca','Ginseng','Saffron','Fenugreek'], benefits: ['Boosts libido naturally','Hormone balance','Energy & mood lift','Confidence'], description: 'A plant-based formula crafted for women — reignite desire, intimacy and confidence.', servings: '60 Capsules', dosage: '1 capsule daily' },
  { slug: 'gas-relief', name: 'Gas Relief Capsules', tagline: 'Bloating? Solved.', category: 'Gut Health', img: 'https://www.zeroharm.in/cdn/shop/files/gas-relief-4312314.jpg?v=1766168169&width=533', gallery: ['https://www.zeroharm.in/cdn/shop/files/gas-relief-4312314.jpg?v=1766168169&width=533'], rating: 4.78, reviews: 69, price: 999, oldPrice: 1499, discount: 33, ingredients: ['Digestive Enzymes','Probiotics','Fennel','Ginger'], benefits: ['Fast gas relief','Reduces bloating','Improves digestion','Plant-based'], description: 'Pre + probiotics + enzymes — your fast lane out of bloating and gas.', servings: '60 Capsules', dosage: '1-2 capsules after meals' },
]

export function getProduct(slug) {
  return PRODUCTS.find(p => p.slug === slug)
}

export const COLLECTIONS = {
  'all': { title: 'All Products', subtitle: 'Explore our complete range of plant-based nano-formulated wellness essentials.', match: () => true },
  'best-sellers': { title: 'Best Sellers', subtitle: 'Most-loved formulas trusted by thousands of customers across India.', match: (p) => p.reviews > 100 },
  'new-arrivals': { title: 'New Arrivals', subtitle: 'Freshly launched plant-powered nano supplements.', match: (p, i, arr) => arr.indexOf(p) >= arr.length - 8 },
  'mens-health': { title: "Men's Health Supplements", subtitle: 'Stamina, vigour, performance — naturally.', match: (p) => p.category === "Men's Health" },
  'womens-health': { title: "Women's Health Supplements", subtitle: 'Fertility, hormonal balance, and beauty from within.', match: (p) => p.category === "Women's Health" },
  'gut-health': { title: 'Gut Health & Digestive Care', subtitle: 'Probiotics, prebiotics, enzymes — for a happy gut.', match: (p) => p.category === 'Gut Health' },
  'lung-health': { title: 'Lung Health', subtitle: 'Detox, repair and breathe easy.', match: (p) => p.category === 'Lung Health' },
  'beauty': { title: 'Beauty & Skincare', subtitle: 'Glow from within with Ayurvedic skin solutions.', match: (p) => p.category === 'Beauty' },
  'diabetic-care': { title: 'Diabetic Care', subtitle: 'Smart glucose management with plant power.', match: (p) => p.category === 'Diabetic Care' },
  'heart-health': { title: 'Heart Health', subtitle: 'Cardio-supportive Ayurvedic formulas.', match: (p) => p.category === 'Heart Health' },
  'wellness': { title: 'Wellness Essentials', subtitle: 'Sleep, stress, recovery — daily wellness staples.', match: (p) => p.category === 'Wellness' },
}

export function getCollection(slug) {
  const c = COLLECTIONS[slug]
  if (!c) return null
  const products = PRODUCTS.filter((p, i, arr) => c.match(p, i, arr))
  return { ...c, slug, products }
}

export function searchProducts(query) {
  const q = (query || '').toLowerCase().trim()
  if (!q) return []
  return PRODUCTS.filter(p => {
    const haystack = [p.name, p.tagline, p.category, p.description, ...(p.ingredients || []), ...(p.benefits || [])].join(' ').toLowerCase()
    return haystack.includes(q)
  })
}
