// Shared product catalog
export const PRODUCTS = [
  { slug: 'focusiq', name: 'FocusIQ', tagline: 'Brain & Focus Support', category: 'Wellness', img: '/Product Image/1.jpg', gallery: ['/Product Image/1.jpg', '/Product Image/19.jpg'], rating: 4.6, reviews: 245, price: 2300, oldPrice: 2500, discount: 8, ingredients: ['Brahmi', 'Bacopa Monnieri', 'Shankhpushpi', "Lion's Mane"], benefits: ['Enhances memory & recall', 'Improves focus & concentration', 'Supports mental clarity', 'Boosts cognitive performance'], description: 'Supports memory, concentration, mental clarity, and cognitive performance. A smart daily blend for peak mental output.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after lunch.' },
  { slug: 'calmcore', name: 'CalmCore', tagline: 'Stress & Relaxation Support', category: 'Wellness', img: '/Product Image/2.jpg', gallery: ['/Product Image/2.jpg', '/Product Image/19.jpg'], rating: 4.5, reviews: 189, price: 2500, oldPrice: 2800, discount: 11, ingredients: ['Ashwagandha', 'Chamomile', 'L-Theanine', 'Holy Basil'], benefits: ['Reduces stress & anxiety', 'Promotes emotional balance', 'Supports relaxation', 'Improves mood naturally'], description: 'Helps manage stress, promotes relaxation, and supports emotional balance. Designed for calm clarity in a busy world.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'sleepzen', name: 'SleepZen', tagline: 'Deep & Restful Sleep', category: 'Wellness', img: '/Product Image/3.jpg', gallery: ['/Product Image/3.jpg', '/Product Image/19.jpg'], rating: 4.7, reviews: 312, price: 1200, oldPrice: 1400, discount: 14, ingredients: ['Melatonin', 'Valerian Root', 'Ashwagandha', 'Passionflower'], benefits: ['Promotes restful sleep', 'Reduces sleep latency', 'Supports healthy sleep cycles', 'Wakes you refreshed'], description: 'Promotes restful sleep, relaxation, and healthy sleep cycles. Wake up energised and refreshed every morning.', servings: '60 Capsules', dosage: '2 capsules 30–60 minutes before bedtime.' },
  { slug: 'gutglow', name: 'GutGlow', tagline: 'Gut Health & Digestion', category: 'Gut Health', img: '/Product Image/4.jpg', gallery: ['/Product Image/4.jpg', '/Product Image/19.jpg'], rating: 4.4, reviews: 156, price: 999, oldPrice: 1000, discount: 0, ingredients: ['Lactobacillus', 'Bifidobacterium', 'Prebiotic Fiber', 'Ginger'], benefits: ['Improves digestion', 'Balances gut microbiome', 'Reduces bloating', 'Enhances nutrient absorption'], description: 'Supports digestion, gut microbiome balance, and nutrient absorption. A daily gut companion for a happier, lighter you.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'immunoshield', name: 'ImmunoShield', tagline: 'Immunity Booster', category: 'Wellness', img: '/Product Image/5.jpg', gallery: ['/Product Image/5.jpg', '/Product Image/19.jpg'], rating: 4.6, reviews: 278, price: 1100, oldPrice: 1400, discount: 21, ingredients: ['Vitamin C', 'Zinc', 'Echinacea', 'Elderberry'], benefits: ['Strengthens immune defenses', 'Fights infections naturally', 'Supports daily wellness', 'Boosts natural immunity'], description: 'Strengthens immune defenses and supports overall wellness. Stay protected with nature-backed immunity support.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'peakfuel', name: 'PeakFuel', tagline: 'Energy & Stamina Booster', category: 'Wellness', img: '/Product Image/6.jpg', gallery: ['/Product Image/6.jpg', '/Product Image/19.jpg'], rating: 4.5, reviews: 203, price: 1200, oldPrice: 1900, discount: 37, ingredients: ['Shilajit', 'Ashwagandha', 'Coenzyme Q10', 'Iron'], benefits: ['Boosts energy levels', 'Enhances endurance', 'Reduces fatigue', 'Supports daily vitality'], description: 'Enhances energy levels, endurance, and daily vitality. Fuel your peak performance from morning to night.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after lunch.' },
  { slug: 'neurolift', name: 'NeuroLift', tagline: 'Cognitive Performance Support', category: 'Wellness', img: '/Product Image/7.jpg', gallery: ['/Product Image/7.jpg', '/Product Image/19.jpg'], rating: 4.3, reviews: 142, price: 2000, oldPrice: 2300, discount: 13, ingredients: ['Ginkgo Biloba', 'Bacopa', 'Phosphatidylserine', 'Omega-3'], benefits: ['Sharpens memory retention', 'Improves brain function', 'Supports focus & clarity', 'Enhances mental performance'], description: 'Supports brain function, focus, memory retention, and mental performance. Lift your mind to its full potential.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after lunch.' },
  { slug: 'heartguard', name: 'HeartGuard', tagline: 'Heart Health Support', category: 'Heart Health', img: '/Product Image/8.jpg', gallery: ['/Product Image/8.jpg', '/Product Image/19.jpg'], rating: 4.8, reviews: 98, price: 500, oldPrice: 750, discount: 33, ingredients: ['Omega-3', 'CoQ10', 'Magnesium', 'Garlic Extract'], benefits: ['Supports cardiovascular health', 'Promotes healthy circulation', 'Maintains healthy cholesterol', 'Heart-protective antioxidants'], description: 'Supports cardiovascular health, circulation, and healthy cholesterol levels. A daily shield for your heart.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'activejoint', name: 'ActiveJoint', tagline: 'Joint Flexibility & Mobility', category: 'Wellness', img: '/Product Image/9.jpg', gallery: ['/Product Image/9.jpg', '/Product Image/19.jpg'], rating: 4.5, reviews: 167, price: 3000, oldPrice: 3200, discount: 6, ingredients: ['Glucosamine', 'Chondroitin', 'Boswellia', 'Turmeric'], benefits: ['Improves joint flexibility', 'Supports cartilage health', 'Reduces stiffness', 'Enhances mobility'], description: 'Promotes joint flexibility, mobility, and cartilage health. Move freely and live actively every day.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'vitadaily', name: 'VitaDaily', tagline: 'Complete Daily Multivitamin', category: 'Wellness', img: '/Product Image/10.jpg', gallery: ['/Product Image/10.jpg', '/Product Image/19.jpg'], rating: 4.4, reviews: 234, price: 1000, oldPrice: 1200, discount: 17, ingredients: ['Vitamin A', 'B Complex', 'Vitamin C', 'Vitamin D3'], benefits: ['Fills nutritional gaps', 'Supports daily energy', 'Boosts overall health', 'Essential micronutrients'], description: 'Provides essential vitamins and minerals for daily nutritional support. Your complete daily nutrition in one capsule.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'livercare', name: 'LiverCare', tagline: 'Liver Detox & Support', category: 'Wellness', img: '/Product Image/11.jpg', gallery: ['/Product Image/11.jpg', '/Product Image/19.jpg'], rating: 4.7, reviews: 189, price: 1500, oldPrice: 1700, discount: 12, ingredients: ['Milk Thistle', 'Dandelion Root', 'Artichoke Extract', 'Turmeric'], benefits: ['Detoxifies liver naturally', 'Supports liver function', 'Promotes cell regeneration', 'Protects against toxins'], description: 'Supports liver detoxification, function, and overall liver wellness. Give your liver the daily care it deserves.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'sugarbalance', name: 'SugarBalance', tagline: 'Healthy Blood Sugar Support', category: 'Diabetic Care', img: '/Product Image/12.jpg', gallery: ['/Product Image/12.jpg', '/Product Image/19.jpg'], rating: 4.6, reviews: 211, price: 1200, oldPrice: 1300, discount: 8, ingredients: ['Berberine', 'Cinnamon', 'Bitter Melon', 'Fenugreek'], benefits: ['Maintains healthy blood sugar', 'Improves insulin sensitivity', 'Supports metabolic health', 'Reduces cravings'], description: 'Helps maintain healthy blood sugar levels and metabolic balance. A natural approach to sugar management.', servings: '60 Capsules', dosage: '1 capsule before breakfast and 1 capsule before dinner.' },
  { slug: 'hairfuel', name: 'HairFuel', tagline: 'Hair Growth & Strength', category: 'Beauty', img: '/Product Image/13.jpg', gallery: ['/Product Image/13.jpg', '/Product Image/19.jpg'], rating: 4.5, reviews: 178, price: 1400, oldPrice: 1600, discount: 13, ingredients: ['Biotin', 'Keratin', 'Amla', 'Bhringraj'], benefits: ['Strengthens hair follicles', 'Reduces hair fall', 'Promotes new growth', 'Nourishes scalp health'], description: 'Nourishes hair follicles and supports stronger, healthier hair growth. Your daily formula for thick, vibrant hair.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'glowcollagen', name: 'GlowCollagen', tagline: 'Skin Radiance & Elasticity', category: 'Beauty', img: '/Product Image/14.jpg', gallery: ['/Product Image/14.jpg', '/Product Image/19.jpg'], rating: 4.7, reviews: 256, price: 1500, oldPrice: 1800, discount: 17, ingredients: ['Marine Collagen', 'Vitamin C', 'Hyaluronic Acid', 'Glutathione'], benefits: ['Improves skin elasticity', 'Hydrates from within', 'Reduces fine lines', 'Enhances natural radiance'], description: 'Supports skin elasticity, hydration, and a healthy radiant appearance. Glow from within with every capsule.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'detoxpro', name: 'DetoxPro', tagline: 'Daily Detox & Cleanse', category: 'Wellness', img: '/Product Image/15.jpg', gallery: ['/Product Image/15.jpg', '/Product Image/19.jpg'], rating: 4.4, reviews: 134, price: 1400, oldPrice: 1600, discount: 13, ingredients: ['Activated Charcoal', 'Triphala', 'Neem', 'Spirulina'], benefits: ['Flushes toxins naturally', 'Supports digestive wellness', 'Clears skin from within', 'Daily cleansing support'], description: 'Supports natural detoxification processes and digestive wellness. Reset your body with a powerful daily cleanse.', servings: '60 Capsules', dosage: '1 capsule before breakfast and 1 capsule before dinner.' },
  { slug: 'fatburn-plus', name: 'FatBurn+', tagline: 'Smart Weight Management', category: 'Weight Management', img: '/Product Image/16.jpg', gallery: ['/Product Image/16.jpg', '/Product Image/19.jpg'], rating: 4.5, reviews: 302, price: 1000, oldPrice: 1200, discount: 17, ingredients: ['Green Tea Extract', 'Garcinia Cambogia', 'L-Carnitine', 'CLA'], benefits: ['Boosts metabolism', 'Supports fat utilization', 'Controls appetite', 'Aids healthy weight goals'], description: 'Supports metabolism, fat utilization, and healthy weight goals. A smart daily companion for your weight journey.', servings: '60 Capsules', dosage: '1 capsule 30 minutes before breakfast and 1 capsule 30 minutes before lunch.' },
  { slug: 'bonestrength', name: 'BoneStrength', tagline: 'Bone Density & Strength', category: 'Wellness', img: '/Product Image/17.jpg', gallery: ['/Product Image/17.jpg', '/Product Image/19.jpg'], rating: 4.6, reviews: 145, price: 1200, oldPrice: 1300, discount: 8, ingredients: ['Calcium', 'Vitamin D3', 'Vitamin K2', 'Magnesium'], benefits: ['Improves bone density', 'Prevents calcium deficiency', 'Supports skeletal strength', 'Reduces fracture risk'], description: 'Supports bone density, strength, and calcium utilization. Build stronger bones for a more active life.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
  { slug: 'eyevision', name: 'EyeVision', tagline: 'Eye Health & Visual Clarity', category: 'Wellness', img: '/Product Image/18.jpg', gallery: ['/Product Image/18.jpg', '/Product Image/19.jpg'], rating: 4.7, reviews: 121, price: 800, oldPrice: 1000, discount: 20, ingredients: ['Lutein', 'Zeaxanthin', 'Vitamin A', 'Bilberry Extract'], benefits: ['Protects eye health', 'Improves visual clarity', 'Reduces digital eye strain', 'Antioxidant eye defense'], description: 'Supports vision health, eye comfort, and protection from oxidative stress. See clearer, feel better every day.', servings: '60 Capsules', dosage: '1 capsule after breakfast and 1 capsule after dinner.' },
]

export function getProduct(slug) {
  return PRODUCTS.find(p => p.slug === slug)
}

export const COLLECTIONS = {
  'all': { title: 'All Products', subtitle: 'Explore our complete range of plant-based nano-formulated wellness essentials.', match: () => true },
  'best-sellers': { title: 'Best Sellers', subtitle: 'Most-loved formulas trusted by thousands of customers across India.', match: (p) => p.reviews > 150 },
  'new-arrivals': { title: 'New Arrivals', subtitle: 'Freshly launched plant-powered nano supplements.', match: (p, i, arr) => arr.indexOf(p) >= arr.length - 8 },
  'gut-health': { title: 'Gut Health & Digestion', subtitle: 'Probiotics, prebiotics — for a happy, balanced gut.', match: (p) => p.category === 'Gut Health' },
  'beauty': { title: 'Beauty & Skincare', subtitle: 'Glow, shine and radiate from within.', match: (p) => p.category === 'Beauty' },
  'diabetic-care': { title: 'Diabetic Care', subtitle: 'Smart blood sugar management with plant power.', match: (p) => p.category === 'Diabetic Care' },
  'heart-health': { title: 'Heart Health', subtitle: 'Cardio-supportive formulas for a stronger heart.', match: (p) => p.category === 'Heart Health' },
  'weight-management': { title: 'Weight Management', subtitle: 'Support your healthy weight journey naturally.', match: (p) => p.category === 'Weight Management' },
  'wellness': { title: 'Wellness Essentials', subtitle: 'Sleep, stress, energy, immunity — daily wellness staples.', match: (p) => p.category === 'Wellness' },
}

export function getCollection(slug) {
  const c = COLLECTIONS[slug]
  if (!c) return null
  const products = PRODUCTS.filter((p, i, arr) => c.match(p, i, arr))
  return { ...c, slug, products }
}

export function searchProducts(query) {
  const q = (query || '').toLowerCase().trim()
  if (!q) return []
  return PRODUCTS.filter(p => {
    const haystack = [p.name, p.tagline, p.category, p.description, ...(p.ingredients || []), ...(p.benefits || [])].join(' ').toLowerCase()
    return haystack.includes(q)
  })
}
